modLoader = "javafml"
loaderVersion = "[35,)"
license = "Unlicense"
issueTrackerURL = "https://github.com/SwanX1/Claimr/issues"

[[mods]]
modId = "claimr"
version = "1.0.2"
displayName = "Claimr"
updateJSONURL = "https://cernavskis.dev/api/claimr.json"
displayURL = "https://github.com/SwanX1/Claimr"
logoFile="claimr-logo.png"
authors = "SwanX1"
description = '''
A server-side chunk claiming mod akin to FTB Chunks, but is not required on the client.
Made for the Slightly Vanilla Flavoured server.
'''

[[dependencies.claimr]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.claimr]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.16.4,1.17)"

[[dependencies.claimr]]
mandatory = false
modId = "ftbranks"
ordering = "AFTER"
side = "SERVER"
versionRange = "[1.0.0,)"