modLoader = "javafml"
loaderVersion = "[35,)"
license = "Unlicense"
issueTrackerURL = "https://github.com/SwanX1/Claimr/issues"

[[mods]]
modId = "claimr"
version = "0.0.1-SNAPSHOT"
displayName = "Claimr"
updateJSONURL = "https://cernavskis.dev/api/claimr.json"
displayURL = "https://github.com/SwanX1/Claimr"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png"
# A text field displayed in the mod UI
#credits="Idea made when i was looking for a server-side claim mod"
authors = "SwanX1"
description = '''
Idk
'''

[[dependencies.claimr]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.claimr]]
mandatory = true
modId = "minecraft"
ordering = "NONE"
side = "BOTH"
versionRange = "[1.16.4,1.17)"

[[dependencies.claimr]]
mandatory = false
modId = "ftbranks"
ordering = "AFTER"
side = "SERVER"
versionRange = "[1.0.0,)"