name: Build JAR
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'gradle.properties'
  pull_request:
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'gradle.properties'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Run Gradle Build
        run: ./gradlew build --no-daemon --max-workers 1 --stacktrace --info

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generated JAR
          path: build/libs/
